### ISSUE TITLE
What is the affiliation between koodikoulu and Reaktor/Futurice?

### ISSUE THREAD

**Issue by melonmanchan** [koodikoulu/koodikoulu#12]
Hi! I have a couple of quick questions about Koodikoulu and their various sponsors/affiliates/whatever you want to call them.

From what I could gather from the 'story' page and other articles, Koodikoulu first began as a strictly in-house event at Reaktor, is that right? Is koodikoulu currently sanctioned by FNBE/similiar government entities? Are the teachers current Reaktor/Futurice employees or volunteers? To what extent are the various costs and such footed by Reaktor/Futurice?

**Comment by raimohanska** [comment]
Firstly, Koodikoulu is not an official organization of any kind. Thus it cannot directly receive funding from government or any other institution. Koodikoulu events are organized by individuals, companies and organizations such as schools and libraries. Reaktor and Futurice, in collaboration, have implemented the Koodikoulu web site to make event organization as easy as possible and to collect all the events on a single page.

We invite everyone to collaborate!
